# Esta sección configura cómo Netlify debe construir tu sitio.
[build]
  # El comando que se ejecuta para instalar las dependencias.
  command = "npm install"
  # Directorio donde Netlify buscará los archivos estáticos de tu sitio (si los tuvieras).
  # Incluso si solo usas funciones, es buena práctica definir uno.
  publish = "public"

# Esta sección es crucial para configurar las funciones de Netlify.
[functions]
  # Le dice a Netlify en qué carpeta buscar tus funciones.
  # Tu función API.js está dentro de "netlify/functions".
  directory = "netlify/functions"
